name: "Create Docker packages"

on: [ "push" ]

jobs:
  build-master:
    name: "Build from master branch"
    runs-on: "ubuntu-latest"

    steps:

      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          ref: "master"

      - name: "Set up Docker Buildx"
        id: "buildx"
        uses: "docker/setup-buildx-action@v2"

      - name: "Login to GitHub Container Registry"
        uses: "docker/login-action@v2"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Login to DockerHub Container Registry"
        uses: "docker/login-action@v2"
        with:
          username: "dreamscached"
          password: "${{ secrets.DOCKER_HUB_TOKEN }}"

      - name: "Build Docker image"
        uses: docker/build-push-action@v2
        with:
          builder: "${{ steps.buildx.outputs.name }}"
          file: "Dockerfile"
          tags: |
            ghcr.io/dreamscached/herokude:master,
            dreamscached/herokude:master
          context: .
          push: true

  build-minimal:
    name: "Build from minimal branch"
    runs-on: "ubuntu-latest"

    steps:

      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          ref: "minimal"

      - name: "Set up Docker Buildx"
        id: "buildx"
        uses: "docker/setup-buildx-action@v2"

      - name: "Login to GitHub Container Registry"
        uses: "docker/login-action@v2"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Login to DockerHub Container Registry"
        uses: "docker/login-action@v2"
        with:
          username: "dreamscached"
          password: "${{ secrets.DOCKER_HUB_TOKEN }}"

      - name: "Build Docker image"
        uses: docker/build-push-action@v2
        with:
          builder: "${{ steps.buildx.outputs.name }}"
          file: "Dockerfile"
          tags: |
            ghcr.io/dreamscached/herokude:minimal,
            dreamscached/herokude:minimal
          context: .
          push: true

  build-xterm:
    name: "Build from xterm branch"
    runs-on: "ubuntu-latest"

    steps:

      - name: "Checkout"
        uses: "actions/checkout@v3"
        with:
          ref: "xterm"

      - name: "Set up Docker Buildx"
        id: "buildx"
        uses: "docker/setup-buildx-action@v2"

      - name: "Login to GitHub Container Registry"
        uses: "docker/login-action@v2"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Login to DockerHub Container Registry"
        uses: "docker/login-action@v2"
        with:
          username: "dreamscached"
          password: "${{ secrets.DOCKER_HUB_TOKEN }}"

      - name: "Build Docker image"
        uses: docker/build-push-action@v2
        with:
          builder: "${{ steps.buildx.outputs.name }}"
          file: "Dockerfile"
          tags: |
            ghcr.io/dreamscached/herokude:xterm,
            dreamscached/herokude:xterm
          context: .
          push: true