name: "Create Docker packages"

on:
  push:
    branches: [ "master", "minimal", "xterm" ]

jobs:
  build:
    name: "Build"
    steps:

      - name: "Checkout"
        uses: "actions/checkout@v3"

      - name: "Extract branch name"
        id: "branch"
        shell: "bash"
        run: |
          echo "::set-output name=branch::$(echo "${GITHUB_REF#refs/heads/}")"

      - name: "Set up Docker Buildx"
        id: "buildx"
        uses: "docker/setup-buildx-action@v2"

      - name: "Login to GitHub Container Registry"
        uses: "docker/login-action@v2"
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Login to DockerHub Container Registry"
        uses: "docker/login-action@v2"
        with:
          username: "dreamscached"
          password: "${{ secrets.DOCKER_HUB_TOKEN }}"

      - name: "Build Docker image"
        uses: docker/build-push-action@v2
        with:
          builder: "${{ steps.buildx.outputs.name }}"
          file: "Dockerfile"
          tags: |
            ghcr.io/dreamscached/herokude:${{ steps.branch.outputs.branch }},
            dreamscached/herokude:${{ steps.branch.outputs.branch }}
          context: .
          push: true